### ISSUE TITLE
Docker image not avalaible

### ISSUE THREAD

**Issue by crossmax** [pashi/docker-garmin-antfs#1]
Hi pashi!
Thanks for sharing your antfs docker.
I'm creating my antfs container but seems your docker image already not available.

Can you publish it again?
Thanks

**Comment by pashi** [comment]
Hi crossmax,

As you might notice this docker container have built 7 years ago and python version 2.7 have already end of life. So I am not publish these legacy containers. This repository include Dockerfile how it was build on that time so you could try yourself to build container.

**Comment by pashi** [comment]
published new version of container docker.io/pashi/garmin-antfs.
